export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  flavor: string;
  nicotine: string;
  price: number;
  badge: string;
  image: string;
};

const imageVersion = "v3";

export const products: Product[] = [
  {
    id: "sku_1",
    slug: "frozen-lab-device-18000",
    name: "Frozen Lab Device 18000",
    brand: "Frozen Lab",
    flavor: "Arctic Mint",
    nicotine: "5%",
    price: 18.99,
    badge: "Top Rated",
    image: "/images/realpro-1.svg?" + imageVersion,
  },
  {
    id: "sku_2",
    slug: "nova-pro-18000",
    name: "Mango Torch 18000",
    brand: "Nova",
    flavor: "Mango Torch",
    nicotine: "5%",
    price: 19.99,
    badge: "Top Rated",
    image: "/images/realpro-2.svg?" + imageVersion,
  },
  {
    id: "sku_3",
    slug: "crystal-rush-15000",
    name: "Crystal Rush 15000",
    brand: "Crystal",
    flavor: "Watermelon Chill",
    nicotine: "5%",
    price: 16.99,
    badge: "New",
    image: "/images/realpro-3.svg?" + imageVersion,
  },
  {
    id: "sku_4",
    slug: "arctic-glow-12000",
    name: "Arctic Glow 12000",
    brand: "Frozen Lab",
    flavor: "Citrus Ice",
    nicotine: "3%",
    price: 15.99,
    badge: "Limited",
    image: "/images/realpro-4.svg?" + imageVersion,
  },
  {
    id: "sku_5",
    slug: "nova-pack-trio",
    name: "Nova Pack Trio",
    brand: "Nova",
    flavor: "Strawberry Ice",
    nicotine: "5%",
    price: 44.0,
    badge: "Best Value",
    image: "/images/realpro-5.svg?" + imageVersion,
  },
  {
    id: "sku_6",
    slug: "frozen-lab-polar",
    name: "Frozen Lab Polar",
    brand: "Frozen Lab",
    flavor: "Peach Freeze",
    nicotine: "5%",
    price: 18.5,
    badge: "Seasonal",
    image: "/images/realpro-6.svg?" + imageVersion,
  },
  {
    id: "sku_7",
    slug: "citrus-ice-16000",
    name: "Citrus Ice 16000",
    brand: "Nova",
    flavor: "Citrus Ice",
    nicotine: "5%",
    price: 17.99,
    badge: "Fresh",
    image: "/images/realpro-1.svg?" + imageVersion,
  },
  {
    id: "sku_8",
    slug: "mango-aurora-16000",
    name: "Mango Aurora 16000",
    brand: "Frozen Lab",
    flavor: "Mango Aurora",
    nicotine: "5%",
    price: 17.5,
    badge: "Popular",
    image: "/images/realpro-2.svg?" + imageVersion,
  },
  {
    id: "sku_9",
    slug: "blue-razz-15000",
    name: "Blue Razz 15000",
    brand: "Nova",
    flavor: "Blue Razz",
    nicotine: "5%",
    price: 16.49,
    badge: "New",
    image: "/images/realpro-3.svg?" + imageVersion,
  },
  {
    id: "sku_10",
    slug: "strawberry-ice-15000",
    name: "Strawberry Ice 15000",
    brand: "Frozen Lab",
    flavor: "Strawberry Ice",
    nicotine: "5%",
    price: 16.49,
    badge: "Top Rated",
    image: "/images/realpro-4.svg?" + imageVersion,
  },
  {
    id: "sku_11",
    slug: "cola-frost-12000",
    name: "Cola Frost 12000",
    brand: "Nova",
    flavor: "Cola Frost",
    nicotine: "3%",
    price: 15.49,
    badge: "Limited",
    image: "/images/realpro-1.svg?" + imageVersion,
  },
  {
    id: "sku_12",
    slug: "pineapple-rush-15000",
    name: "Pineapple Rush 15000",
    brand: "Frozen Lab",
    flavor: "Pineapple Rush",
    nicotine: "5%",
    price: 16.99,
    badge: "Popular",
    image: "/images/realpro-2.svg?" + imageVersion,
  },
  {
    id: "sku_13",
    slug: "grape-chill-15000",
    name: "Grape Chill 15000",
    brand: "Nova",
    flavor: "Grape Chill",
    nicotine: "5%",
    price: 16.99,
    badge: "New",
    image: "/images/realpro-3.svg?" + imageVersion,
  },
  {
    id: "sku_14",
    slug: "mint-pulse-12000",
    name: "Mint Pulse 12000",
    brand: "Frozen Lab",
    flavor: "Mint",
    nicotine: "3%",
    price: 15.49,
    badge: "Best Value",
    image: "/images/realpro-4.svg?" + imageVersion,
  },
  {
    id: "sku_15",
    slug: "peach-freeze-15000",
    name: "Peach Freeze 15000",
    brand: "Nova",
    flavor: "Peach Freeze",
    nicotine: "5%",
    price: 16.99,
    badge: "Seasonal",
    image: "/images/realpro-5.svg?" + imageVersion,
  },
  {
    id: "sku_16",
    slug: "watermelon-wave-15000",
    name: "Watermelon Wave 15000",
    brand: "Frozen Lab",
    flavor: "Watermelon Wave",
    nicotine: "5%",
    price: 16.99,
    badge: "Fresh",
    image: "/images/realpro-6.svg?" + imageVersion,
  },
  {
    id: "sku_17",
    slug: "berry-mix-12000",
    name: "Berry Mix 12000",
    brand: "Nova",
    flavor: "Berry Mix",
    nicotine: "3%",
    price: 15.99,
    badge: "Popular",
    image: "/images/realpro-1.svg?" + imageVersion,
  },
  {
    id: "sku_18",
    slug: "citrus-surge-12000",
    name: "Citrus Surge 12000",
    brand: "Frozen Lab",
    flavor: "Citrus",
    nicotine: "3%",
    price: 15.49,
    badge: "New",
    image: "/images/realpro-2.svg?" + imageVersion,
  },
  {
    id: "sku_19",
    slug: "mango-splash-15000",
    name: "Mango Splash 15000",
    brand: "Nova",
    flavor: "Mango",
    nicotine: "5%",
    price: 16.99,
    badge: "Top Rated",
    image: "/images/realpro-3.svg?" + imageVersion,
  },
  {
    id: "sku_20",
    slug: "arctic-ice-15000",
    name: "Arctic Ice 15000",
    brand: "Frozen Lab",
    flavor: "Arctic Ice",
    nicotine: "5%",
    price: 16.99,
    badge: "Seasonal",
    image: "/images/realpro-4.svg?" + imageVersion,
  },
];

export const featured = [products[2], products[1], products[0]];
